replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: "15-alpine"

fullnameOverride: "postgres-service"

service:
  type: ClusterIP
  port: 5432

env:
  POSTGRES_USER: "ShaiAdmin"
  POSTGRES_DB: "dogopsdb"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
<<<<<<< HEAD
    memory: 256Mi

persistence:
  enabled: true
  size: 2Gi
=======
    memory: 256Mi
>>>>>>> master
