replicaCount: 1

image:
  repository: postgres
  tag: "15-alpine"
  pullPolicy: IfNotPresent

env:
  POSTGRES_DB: "dogopsdb"
  POSTGRES_USER: "ShaiAdmin"

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

persistence:
  enabled: true
  size: "2Gi"